DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  POINTNAVV1:
    DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
SIMULATOR:
  SCENE: data/scene_datasets/gibson/Lynchburg.glb
  TURN_ANGLE: 30
  AGENT_0:
    SENSORS: ["RGB_SENSOR"] 
