#!/bin/bash
#PBS -q eng-instruction   
#PBS -l walltime=00:30:00,nodes=1:ppn=16:V100
#PBS -N train_action_predictor
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
#PBS -m bea
#PBS -M dpshah2@illinois.edu
. /opt/modules/default/init/bash # NEEDED to add module commands to shell
cd /home/dpshah2/scratch/ece598sg-project/SPTM-Tensorflow2/
module load singularity
singularity exec --nv habitat.simg
 /bin/bash ./src/run.sh
